version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links: 
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
  jenkins:
    container_name: jenkins
    privileged: true
    user: root
    depends_on:
      - nginx
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
